# Enter configuration items here.
wallet_server: http://YOUR_SERVER:8090
wallet_version: v2
rosetta_server: http://YOUR_SERVER:8080
ogmios_server: YOUR_SERVER:1337
db_sync_server: localhost

# Executable paths
cardano_cli_path: YOUR_PATH_TO_CLI
cardano_address_path: YOUR_PATH_TO_CLI
